# Generated by Django 5.2.8 on 2025-11-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Internal name used in template tag', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('external_url', models.CharField(blank=True, help_text='Явный URL, например /about/ или https://...', max_length=1024)),
                ('named_url', models.CharField(blank=True, help_text="Имя url (reverse name), например 'app:view_name'", max_length=255)),
                ('named_args', models.JSONField(blank=True, help_text='Позиционные args для reverse в виде JSON-массива, например [1]', null=True)),
                ('named_kwargs', models.JSONField(blank=True, help_text='Ключевые kwargs для reverse в виде JSON-объекта, например {"slug": "x"}', null=True)),
                ('order', models.IntegerField(default=0, help_text='Порядок сортировки в одном уровне')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Открывать ссылку в новой вкладке')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_app.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_app.menuitem')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ('order', 'id'),
            },
        ),
    ]
